name: Renovate

on:
  schedule:
    - cron: "0 4 * * 6" # Saturdays at 4 AM UTC
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v46.1.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
